name: Build React Native Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'  # Use the version compatible with your Android Gradle plugin

    # Step 3: Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure compatibility with your package.json


    # Step 4: Install Yarn
    - name: Install Yarn
      run: npm install -g yarn

    # Step 5: Install project dependencies
    - name: Install dependencies
      run: yarn install

    # Step 6: Set up Android environment
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33  # Adjust based on your app's requirements
        build-tools: 33.0.2
        # ndk: '23.1.7779620'  # Optional, only if your app uses NDK
        cache: true

    # Step 7: Grant execute permissions to gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android

    # Step 7.1: Build the Android APK
    - name: Build APK
      run: ./gradlew assembleRelease
      working-directory: android

    # Step 8: Archive the APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
